
server:
  port: 0

spring:
  application:
    name: member-service

  h2:
    console:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.hostname}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

