
server:
  port: 0

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
#        lb, health-check
      routes:
        - id: member-serivce
          uri: http://localhost:8091
          predicates:
            - Path=/members/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


