
server:
  port: 8000

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
#        lb, health-check
      routes:
        - id: member-serivce
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/members/**

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.hostname}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


