
server:
  port: 8000

spring:
  application:
    name: gateway-service

#  refactor spring.config
  config:
    import: classpath:jwt.yml

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8080"
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: login
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/login
            - Method=POST

        - id: join
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/members
            - Method=POST

        - id: member-serivce
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/members/**
          filters:
            - CustomAuthHeaderFilter
#       ws 분리
        - id: chat-service
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/chats/**
#          filters:
#            - CustomAuthHeaderFilter

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.hostname}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


