spring:
  application:
    name: chat-service

server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.cloud.client.hostname}:${random.value}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

